(() => {
  const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const fmt=s=>{if(!s)return'';const d=new Date(s+'T12:00:00');return Number.isNaN(d.getTime())?s:d.toLocaleDateString('fr-FR',{day:'2-digit',month:'long',year:'numeric'});};
  const desc=(a,b)=>String(b.date||'').localeCompare(String(a.date||''));
  const action=i=>{if(!i.url)return'';const t=i.type==='Vidéo'?'Voir la vidéo':i.type==='À lire'?'Lire la source':'Lire';const ext=/^https?:\/\//i.test(i.url);return `<a class="r-card-link" href="${esc(i.url)}"${ext?' target="_blank" rel="noopener noreferrer"':''}>${t} →</a>`;};
  const card=i=>`<article class="r-card" data-type="${esc(i.type||'Réflexion')}" data-cat="${esc(i.categorie||'')}">${i.image?`<div class="r-card-image"><img src="${esc(i.image)}" alt=""></div>`:''}<div class="r-card-body"><div class="r-card-meta"><span>${esc(i.type||'Réflexion')}</span>${i.categorie?`<span>${esc(i.categorie)}</span>`:''}${i.date?`<time datetime="${esc(i.date)}">${esc(fmt(i.date))}</time>`:''}</div><h3>${esc(i.titre||'Sans titre')}</h3><p>${esc(i.resume||'')}</p>${i.mon_regard?`<p class="r-card-regard"><strong>Mon regard.</strong> ${esc(i.mon_regard)}</p>`:''}<div class="r-card-foot">${i.source?`<span class="r-card-source">${esc(i.source)}</span>`:''}${action(i)}</div></div></article>`;
  const mobile=i=>`<article class="m-card"><div class="r-mobile-meta">${esc(i.type||'Réflexion')}${i.categorie?' · '+esc(i.categorie):''}</div><h3>${esc(i.titre||'Sans titre')}</h3><p>${esc(i.resume||'')}</p>${i.mon_regard?`<p class="r-mobile-regard"><strong>Mon regard.</strong> ${esc(i.mon_regard)}</p>`:''}${action(i)}</article>`;
  const archives=(items,isMobile=false)=>[...new Set(items.map(i=>(i.date||'').slice(0,4)||'Sans date'))].sort((a,b)=>b.localeCompare(a)).map(y=>{const a=items.filter(i=>((i.date||'').slice(0,4)||'Sans date')===y).sort(desc);return `<section class="r-archive-year"><h3>${esc(y)}</h3><div class="${isMobile?'m-cards':'r-grid'}">${a.map(isMobile?mobile:card).join('')}</div></section>`;}).join('');
  function render(items){
    const pub=items.filter(i=>(i.statut||'publie')==='publie').sort(desc), arc=items.filter(i=>i.statut==='archive').sort(desc);
    const d=document.getElementById('reflexions-live-grid'),m=document.getElementById('reflexions-mobile-cards');
    if(d)d.innerHTML=pub.map(card).join('')||'<p class="r-empty-state">Les premiers contenus arrivent bientôt.</p>';
    if(m)m.innerHTML=pub.map(mobile).join('')||'<p class="r-empty-state">Les premiers contenus arrivent bientôt.</p>';
    const c=document.getElementById('reflexions-count');if(c)c.textContent=`${pub.length} contenu${pub.length>1?'s':''}`;
    const bd=document.getElementById('archive-toggle'),bm=document.getElementById('archive-toggle-mobile'),ad=document.getElementById('reflexions-archives'),am=document.getElementById('reflexions-mobile-archives');
    [bd,bm].forEach(b=>{if(!b)return;b.hidden=!arc.length;b.textContent=`Voir les archives (${arc.length})`;b.setAttribute('aria-expanded','false');});
    if(ad)ad.innerHTML=arc.length?archives(arc,false):'';if(am)am.innerHTML=arc.length?archives(arc,true):'';
  }
  function filter(v){document.querySelectorAll('#reflexions-live-grid .r-card').forEach(el=>el.hidden=!(v==='Tous'||el.dataset.type===v||el.dataset.cat===v));document.querySelectorAll('.r-filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===v));}
  function toggle(btn,id){const t=document.getElementById(id);if(!t)return;const open=t.hidden;t.hidden=!open;btn.setAttribute('aria-expanded',String(open));btn.textContent=(open?'Masquer les archives':'Voir les archives')+btn.textContent.replace(/^.*?(\(\d+\))$/,' $1');if(open)t.scrollIntoView({behavior:'smooth',block:'start'});}
  fetch('contenus.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(items=>{render(items);filter('Tous');}).catch(err=>{console.error(err);const msg='<p class="r-error">Impossible de charger les contenus pour le moment.</p>';const d=document.getElementById('reflexions-live-grid');if(d)d.innerHTML=msg;const m=document.getElementById('reflexions-mobile-cards');if(m)m.innerHTML=msg;});
  document.addEventListener('click',e=>{const f=e.target.closest('.r-filter');if(f){e.preventDefault();filter(f.dataset.filter);return;}const a=e.target.closest('#archive-toggle');if(a){e.preventDefault();toggle(a,'reflexions-archives');return;}const am=e.target.closest('#archive-toggle-mobile');if(am){e.preventDefault();toggle(am,'reflexions-mobile-archives');}});
})();
